name: TikTok Auto-Download
on:
  schedule:
    - cron: '*/30 * * * *'  # Comillas cerradas correctamente
  workflow_dispatch:         # Permite ejecución manual
permissions:
  actions: write             # Necesario para upload-artifact
  contents: read

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install yt-dlp
      - name: Run script
        run: python tiktok_downloader.py
      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-videos
          path: videos/
          retention-days: 3  
